-- MySQL Script generated by MySQL Workbench
-- jue 09 sep 2021 14:38:19 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema erp_sap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema erp_sap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `erp_sap` DEFAULT CHARACTER SET armscii8 ;
USE `erp_sap` ;

-- -----------------------------------------------------
-- Table `erp_sap`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_sap`.`auth_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 209
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `erp_sap`.`base_pycountry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_sap`.`base_pycountry` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NULL DEFAULT NULL,
  `fc` DATETIME(6) NULL DEFAULT NULL,
  `fm` DATETIME(6) NULL DEFAULT NULL,
  `uc` INT NULL DEFAULT NULL,
  `um` INT NULL DEFAULT NULL,
  `company_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `erp_sap`.`base_pycurrency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_sap`.`base_pycurrency` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NULL DEFAULT NULL,
  `fc` DATETIME(6) NULL DEFAULT NULL,
  `fm` DATETIME(6) NULL DEFAULT NULL,
  `uc` INT NULL DEFAULT NULL,
  `um` INT NULL DEFAULT NULL,
  `company_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(40) NOT NULL,
  `alias` VARCHAR(40) NOT NULL,
  `symbol` VARCHAR(15) NOT NULL,
  `iso` VARCHAR(30) NOT NULL,
  `position` VARCHAR(64) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `base_pycurrency_country_id_cc40ef07_fk_base_pycountry_id` (`country_id` ASC) VISIBLE,
  CONSTRAINT `base_pycurrency_country_id_cc40ef07_fk_base_pycountry_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `erp_sap`.`base_pycountry` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `erp_sap`.`base_pycompany`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_sap`.`base_pycompany` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NULL DEFAULT NULL,
  `fc` DATETIME(6) NULL DEFAULT NULL,
  `fm` DATETIME(6) NULL DEFAULT NULL,
  `uc` INT NULL DEFAULT NULL,
  `um` INT NULL DEFAULT NULL,
  `company_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(40) NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `street_2` VARCHAR(100) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `postal_code` VARCHAR(255) NOT NULL,
  `social_facebook` VARCHAR(255) NOT NULL,
  `social_instagram` VARCHAR(255) NOT NULL,
  `social_linkedin` VARCHAR(255) NOT NULL,
  `social_youtube` VARCHAR(255) NOT NULL,
  `social_whatsapp` VARCHAR(255) NOT NULL,
  `main_color` VARCHAR(20) NOT NULL,
  `content_wrapper_color` VARCHAR(20) NOT NULL,
  `font_color` VARCHAR(20) NOT NULL,
  `slogan` VARCHAR(250) NOT NULL,
  `logo` VARCHAR(255) NULL DEFAULT NULL,
  `latitude` INT NULL DEFAULT NULL,
  `longitude` INT NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `country_id` INT NOT NULL,
  `currency_id_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `base_pycompany_country_id_6485ce9b_fk_base_pycountry_id` (`country_id` ASC) VISIBLE,
  INDEX `base_pycompany_currency_id_id_cfcb59ea_fk_base_pycurrency_id` (`currency_id_id` ASC) VISIBLE,
  CONSTRAINT `base_pycompany_country_id_6485ce9b_fk_base_pycountry_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `erp_sap`.`base_pycountry` (`id`),
  CONSTRAINT `base_pycompany_currency_id_id_cfcb59ea_fk_base_pycurrency_id`
    FOREIGN KEY (`currency_id_id`)
    REFERENCES `erp_sap`.`base_pycurrency` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `erp_sap`.`base_pypartner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_sap`.`base_pypartner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NULL DEFAULT NULL,
  `fc` DATETIME(6) NULL DEFAULT NULL,
  `fm` DATETIME(6) NULL DEFAULT NULL,
  `uc` INT NULL DEFAULT NULL,
  `um` INT NULL DEFAULT NULL,
  `company_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(40) NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `street_2` VARCHAR(100) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `customer` TINYINT(1) NOT NULL,
  `provider` TINYINT(1) NOT NULL,
  `for_invoice` TINYINT(1) NOT NULL,
  `note` LONGTEXT NULL DEFAULT NULL,
  `not_email` TINYINT(1) NOT NULL,
  `img` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(64) NOT NULL,
  `country_id_id` INT NULL DEFAULT NULL,
  `parent_id_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `base_pypartner_country_id_id_eb4aa718_fk_base_pycountry_id` (`country_id_id` ASC) VISIBLE,
  INDEX `base_pypartner_parent_id_id_2c1e803f_fk_base_pypartner_id` (`parent_id_id` ASC) VISIBLE,
  CONSTRAINT `base_pypartner_country_id_id_eb4aa718_fk_base_pycountry_id`
    FOREIGN KEY (`country_id_id`)
    REFERENCES `erp_sap`.`base_pycountry` (`id`),
  CONSTRAINT `base_pypartner_parent_id_id_2c1e803f_fk_base_pypartner_id`
    FOREIGN KEY (`parent_id_id`)
    REFERENCES `erp_sap`.`base_pypartner` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `erp_sap`.`auth_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_sap`.`auth_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_joined` DATETIME(6) NOT NULL,
  `active` TINYINT(1) NULL DEFAULT NULL,
  `fc` DATETIME(6) NULL DEFAULT NULL,
  `fm` DATETIME(6) NULL DEFAULT NULL,
  `uc` INT NULL DEFAULT NULL,
  `um` INT NULL DEFAULT NULL,
  `company_id` INT NULL DEFAULT NULL,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NOT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NULL DEFAULT NULL,
  `email` VARCHAR(254) NOT NULL,
  `telefono` VARCHAR(255) NULL DEFAULT NULL,
  `celular` VARCHAR(255) NULL DEFAULT NULL,
  `avatar` VARCHAR(255) NULL DEFAULT NULL,
  `active_company_id` INT NOT NULL,
  `partner_id_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `auth_user_is_superuser_a230aa12` (`is_superuser` ASC) VISIBLE,
  INDEX `auth_user_is_staff_99173a39` (`is_staff` ASC) VISIBLE,
  INDEX `auth_user_active_company_id_696dc033_fk_base_pycompany_id` (`active_company_id` ASC) VISIBLE,
  INDEX `auth_user_partner_id_id_a3a46346_fk_base_pypartner_id` (`partner_id_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_active_company_id_696dc033_fk_base_pycompany_id`
    FOREIGN KEY (`active_company_id`)
    REFERENCES `erp_sap`.`base_pycompany` (`id`),
  CONSTRAINT `auth_user_partner_id_id_a3a46346_fk_base_pypartner_id`
    FOREIGN KEY (`partner_id_id`)
    REFERENCES `erp_sap`.`base_pypartner` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `erp_sap`.`auth_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_sap`.`auth_user_user_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pyuser_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_pyuser_id_permission_id_41b08f47_uniq` (`pyuser_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `erp_sap`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_pyuser_id_317033e1_fk_auth_user_id`
    FOREIGN KEY (`pyuser_id`)
    REFERENCES `erp_sap`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `erp_sap`.`base_baseconfig`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_sap`.`base_baseconfig` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `online` TINYINT(1) NOT NULL,
  `open_menu` TINYINT(1) NOT NULL,
  `load_data` TINYINT(1) NOT NULL,
  `type_share` VARCHAR(64) NOT NULL,
  `main_company_id_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `base_baseconfig_main_company_id_id_668d781e_fk_base_pycompany_id` (`main_company_id_id` ASC) VISIBLE,
  CONSTRAINT `base_baseconfig_main_company_id_id_668d781e_fk_base_pycompany_id`
    FOREIGN KEY (`main_company_id_id`)
    REFERENCES `erp_sap`.`base_pycompany` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `erp_sap`.`base_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_sap`.`base_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `slug` VARCHAR(20) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE,
  UNIQUE INDEX `slug` (`slug` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `erp_sap`.`base_pyfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_sap`.`base_pyfile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NULL DEFAULT NULL,
  `fc` DATETIME(6) NULL DEFAULT NULL,
  `fm` DATETIME(6) NULL DEFAULT NULL,
  `uc` INT NULL DEFAULT NULL,
  `um` INT NULL DEFAULT NULL,
  `company_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `note` LONGTEXT NOT NULL,
  `user_id_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `base_pyfile_user_id_id_511233a0_fk_auth_user_id` (`user_id_id` ASC) VISIBLE,
  CONSTRAINT `base_pyfile_user_id_id_511233a0_fk_auth_user_id`
    FOREIGN KEY (`user_id_id`)
    REFERENCES `erp_sap`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `erp_sap`.`base_pymenu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_sap`.`base_pymenu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NULL DEFAULT NULL,
  `fc` DATETIME(6) NULL DEFAULT NULL,
  `fm` DATETIME(6) NULL DEFAULT NULL,
  `uc` INT NULL DEFAULT NULL,
  `um` INT NULL DEFAULT NULL,
  `company_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(40) NOT NULL,
  `link` VARCHAR(100) NOT NULL,
  `sequence` INT NULL DEFAULT NULL,
  `parent_id_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `base_pymenu_parent_id_id_73f73601_fk_base_pymenu_id` (`parent_id_id` ASC) VISIBLE,
  CONSTRAINT `base_pymenu_parent_id_id_73f73601_fk_base_pymenu_id`
    FOREIGN KEY (`parent_id_id`)
    REFERENCES `erp_sap`.`base_pymenu` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `erp_sap`.`base_pyplugin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_sap`.`base_pyplugin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NULL DEFAULT NULL,
  `fc` DATETIME(6) NULL DEFAULT NULL,
  `fm` DATETIME(6) NULL DEFAULT NULL,
  `uc` INT NULL DEFAULT NULL,
  `um` INT NULL DEFAULT NULL,
  `company_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(80) NOT NULL,
  `author` VARCHAR(80) NOT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `installed` TINYINT(1) NULL DEFAULT NULL,
  `website` VARCHAR(180) NULL DEFAULT NULL,
  `color` VARCHAR(20) NULL DEFAULT NULL,
  `fa` VARCHAR(20) NULL DEFAULT NULL,
  `version` VARCHAR(20) NULL DEFAULT NULL,
  `sequence` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `erp_sap`.`base_pyproductcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_sap`.`base_pyproductcategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NULL DEFAULT NULL,
  `fc` DATETIME(6) NULL DEFAULT NULL,
  `fm` DATETIME(6) NULL DEFAULT NULL,
  `uc` INT NULL DEFAULT NULL,
  `um` INT NULL DEFAULT NULL,
  `company_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(40) NOT NULL,
  `parent_id_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `base_pyproductcatego_parent_id_id_64ab9470_fk_base_pypr` (`parent_id_id` ASC) VISIBLE,
  CONSTRAINT `base_pyproductcatego_parent_id_id_64ab9470_fk_base_pypr`
    FOREIGN KEY (`parent_id_id`)
    REFERENCES `erp_sap`.`base_pyproductcategory` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `erp_sap`.`base_pyproduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_sap`.`base_pyproduct` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NULL DEFAULT NULL,
  `fc` DATETIME(6) NULL DEFAULT NULL,
  `fm` DATETIME(6) NULL DEFAULT NULL,
  `uc` INT NULL DEFAULT NULL,
  `um` INT NULL DEFAULT NULL,
  `company_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(80) NOT NULL,
  `code` VARCHAR(80) NOT NULL,
  `bar_code` VARCHAR(80) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `features` LONGTEXT NULL DEFAULT NULL,
  `youtube_video` VARCHAR(300) NULL DEFAULT NULL,
  `img` VARCHAR(255) NULL DEFAULT NULL,
  `web_active` TINYINT(1) NOT NULL,
  `pos_active` TINYINT(1) NOT NULL,
  `share` TINYINT(1) NOT NULL,
  `featured` TINYINT(1) NOT NULL,
  `type` VARCHAR(64) NOT NULL,
  `brand_id_id` INT NULL DEFAULT NULL,
  `category_id_id` INT NULL DEFAULT NULL,
  `uom_id_id` INT NULL DEFAULT NULL,
  `web_category_id_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `base_pyproduct_category_id_id_8315f459_fk_base_pypr` (`category_id_id` ASC) VISIBLE,
  CONSTRAINT `base_pyproduct_category_id_id_8315f459_fk_base_pypr`
    FOREIGN KEY (`category_id_id`)
    REFERENCES `erp_sap`.`base_pyproductcategory` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
